# Generated by Django 5.2.4 on 2025-07-10 11:28

import django.db.models.deletion
import django.utils.timezone
import multiselectfield.db.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ChatExample',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('input_prompt', models.TextField()),
                ('expected_response', models.TextField()),
                ('tags', multiselectfield.db.fields.MultiSelectField(choices=[('correct', 'Correct'), ('misleading', 'Misleading'), ('incomplete', 'Incomplete'), ('slow', 'Slow')], max_length=50)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
            ],
        ),
        migrations.CreateModel(
            name='ChatTrace',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('run_id', models.CharField(max_length=100, unique=True)),
                ('input_prompt', models.TextField()),
                ('output_response', models.TextField()),
                ('status', models.CharField(choices=[('success', 'Success'), ('error', 'Error')], default='success', max_length=20)),
                ('tags', multiselectfield.db.fields.MultiSelectField(blank=True, choices=[('correct', 'Correct'), ('misleading', 'Misleading'), ('incomplete', 'Incomplete'), ('slow', 'Slow')], max_length=50)),
                ('runtime_seconds', models.FloatField(default=0.0)),
                ('trace_data', models.JSONField(default=dict)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='TraceStep',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('step_name', models.CharField(max_length=100)),
                ('step_type', models.CharField(max_length=50)),
                ('input_data', models.JSONField(blank=True, default=dict, null=True)),
                ('output_data', models.JSONField(blank=True, default=dict, null=True)),
                ('start_time', models.DateTimeField()),
                ('end_time', models.DateTimeField()),
                ('runtime_seconds', models.FloatField(default=0.0)),
                ('trace', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='steps', to='tracegptapp.chattrace')),
            ],
            options={
                'ordering': ['start_time'],
            },
        ),
    ]
